services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    container_name: kp-backend-test
    volumes:
      - backend-data-test:/app/data
    ports:
      - "5174:5174"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    container_name: kp-frontend-test
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend-data-test:
