// <auto-generated />
using System;
using KnowledgePortal.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace KnowledgePortal.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260827133607_AddStructuredMultimodalExtraction")]
    partial class AddStructuredMultimodalExtraction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ApiKey", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("key_prefix");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_api_keys");

                    b.HasIndex("KeyPrefix")
                        .HasDatabaseName("ix_api_keys_key_prefix");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_api_keys_user_id");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.Article", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedById")
                        .HasColumnType("text")
                        .HasColumnName("approved_by_id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("reference")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedViaApiKeyId")
                        .HasColumnType("text")
                        .HasColumnName("created_via_api_key_id");

                    b.Property<string>("Excerpt")
                        .HasColumnType("text")
                        .HasColumnName("excerpt");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_id");

                    b.Property<DateTime?>("FtsIndexedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fts_indexed_at");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("indexed_at");

                    b.Property<DateTime?>("LastReviewedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_reviewed_at");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("published_at");

                    b.Property<int?>("ReadTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("read_time_minutes");

                    b.Property<int>("ReviewIntervalDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(90)
                        .HasColumnName("review_interval_days");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VersionCounter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("version_counter");

                    b.HasKey("Id")
                        .HasName("pk_articles");

                    b.HasIndex("ApprovedById")
                        .HasDatabaseName("ix_articles_approved_by_id");

                    b.HasIndex("CreatedViaApiKeyId")
                        .HasDatabaseName("ix_articles_created_via_api_key_id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_articles_external_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_articles_owner_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_articles_slug");

                    b.HasIndex("Status", "FtsIndexedAt")
                        .HasDatabaseName("ix_articles_status_fts_indexed_at");

                    b.HasIndex("Status", "IndexedAt")
                        .HasDatabaseName("ix_articles_status_indexed_at");

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleAttachment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ArticleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("article_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExtractedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("extracted_at");

                    b.Property<int>("ExtractedCharacters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("extracted_characters");

                    b.Property<string>("ExtractedSegmentsJson")
                        .HasColumnType("text")
                        .HasColumnName("extracted_segments_json");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text")
                        .HasColumnName("extracted_text");

                    b.Property<int>("ExtractionCharacterLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50000)
                        .HasColumnName("extraction_character_limit");

                    b.Property<string>("ExtractionError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("extraction_error");

                    b.Property<string>("ExtractionProfile")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("extraction_profile");

                    b.Property<string>("ExtractionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("extraction_status");

                    b.Property<bool>("ExtractionTruncated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("extraction_truncated");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stored_file_name");

                    b.Property<string>("UploadedById")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uploaded_by_id");

                    b.HasKey("Id")
                        .HasName("pk_article_attachments");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("ix_article_attachments_article_id");

                    b.HasIndex("UploadedById")
                        .HasDatabaseName("ix_article_attachments_uploaded_by_id");

                    b.ToTable("article_attachments", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleChunkParent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ArticleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("article_id");

                    b.Property<string>("AttachmentId")
                        .HasColumnType("text")
                        .HasColumnName("attachment_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ParentIndex")
                        .HasColumnType("integer")
                        .HasColumnName("parent_index");

                    b.Property<string>("SourceLocation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_location");

                    b.Property<string>("SourceName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_name");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_type");

                    b.Property<string>("TextHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("text_hash");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer")
                        .HasColumnName("word_count");

                    b.HasKey("Id")
                        .HasName("pk_article_chunk_parents");

                    b.HasIndex("AttachmentId")
                        .HasDatabaseName("ix_article_chunk_parents_attachment_id");

                    b.HasIndex("ArticleId", "ParentIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_article_chunk_parents_article_id_parent_index");

                    b.ToTable("article_chunk_parents", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleComment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ArticleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("article_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_article_comments");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("ix_article_comments_article_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_article_comments_user_id");

                    b.ToTable("article_comments", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleEmbedding", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ArticleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("article_id");

                    b.Property<string>("AttachmentId")
                        .HasColumnType("text")
                        .HasColumnName("attachment_id");

                    b.Property<int>("ChunkIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("chunk_index");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedViaApiKeyId")
                        .HasColumnType("text")
                        .HasColumnName("created_via_api_key_id");

                    b.Property<int>("Dimensions")
                        .HasColumnType("integer")
                        .HasColumnName("dimensions");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_name");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<string>("ParentChunkId")
                        .HasColumnType("text")
                        .HasColumnName("parent_chunk_id");

                    b.Property<string>("SourceLocation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_location");

                    b.Property<string>("SourceName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_name");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_type");

                    b.PrimitiveCollection<string[]>("TagSlugs")
                        .HasColumnType("text[]")
                        .HasColumnName("tag_slugs");

                    b.Property<string>("TextHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_hash");

                    b.HasKey("Id")
                        .HasName("pk_article_embeddings");

                    b.HasIndex("AttachmentId")
                        .HasDatabaseName("ix_article_embeddings_attachment_id");

                    b.HasIndex("ContentType")
                        .HasDatabaseName("ix_article_embeddings_content_type");

                    b.HasIndex("CreatedViaApiKeyId")
                        .HasDatabaseName("ix_article_embeddings_created_via_api_key_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_article_embeddings_owner_id");

                    b.HasIndex("ParentChunkId")
                        .HasDatabaseName("ix_article_embeddings_parent_chunk_id");

                    b.HasIndex("TagSlugs")
                        .HasDatabaseName("ix_article_embeddings_tag_slugs");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TagSlugs"), "gin");

                    b.HasIndex("ArticleId", "ChunkIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_article_embeddings_article_id_chunk_index");

                    b.ToTable("article_embeddings", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleTag", b =>
                {
                    b.Property<string>("ArticleId")
                        .HasColumnType("text")
                        .HasColumnName("article_id");

                    b.Property<string>("TagId")
                        .HasColumnType("text")
                        .HasColumnName("tag_id");

                    b.HasKey("ArticleId", "TagId")
                        .HasName("pk_article_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_article_tags_tag_id");

                    b.ToTable("article_tags", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleVersion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ArticleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("article_id");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("text")
                        .HasColumnName("change_summary");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("changed_by");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_article_versions");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("ix_article_versions_changed_by");

                    b.HasIndex("ArticleId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_article_versions_article_id_version");

                    b.ToTable("article_versions", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleView", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ArticleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("article_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_article_views");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("ix_article_views_article_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_article_views_user_id");

                    b.ToTable("article_views", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleVote", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ArticleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("article_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsHelpful")
                        .HasColumnType("boolean")
                        .HasColumnName("is_helpful");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_article_votes");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_article_votes_user_id");

                    b.HasIndex("ArticleId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_article_votes_article_id_user_id");

                    b.ToTable("article_votes", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.FeaturedLink", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("link_type");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.HasKey("Id")
                        .HasName("pk_featured_links");

                    b.ToTable("featured_links", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.IndexJob", b =>
                {
                    b.Property<string>("ArticleId")
                        .HasColumnType("text")
                        .HasColumnName("article_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("AvailableAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Generation")
                        .HasColumnType("integer")
                        .HasColumnName("generation");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("locked_at");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("locked_by");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ArticleId")
                        .HasName("pk_index_jobs");

                    b.HasIndex("Status", "AvailableAt", "Priority")
                        .HasDatabaseName("ix_index_jobs_status_available_at_priority");

                    b.ToTable("index_jobs", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.LookupValue", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AuthorityWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50)
                        .HasColumnName("authority_weight");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_lookup_values");

                    b.HasIndex("Category", "Value")
                        .IsUnique()
                        .HasDatabaseName("ix_lookup_values_category_value");

                    b.ToTable("lookup_values", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.RagEvaluationDataset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CasesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cases_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ThresholdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("thresholds_json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_rag_evaluation_datasets");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_rag_evaluation_datasets_name");

                    b.ToTable("rag_evaluation_datasets", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.RagEvaluationRun", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CasesSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cases_snapshot_json");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CompletedCases")
                        .HasColumnType("integer")
                        .HasColumnName("completed_cases");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatasetId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dataset_id");

                    b.Property<string>("DatasetVersion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("dataset_version");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("MetricsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metrics_json");

                    b.Property<string>("RequestedById")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requested_by_id");

                    b.Property<string>("ResultsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("results_json");

                    b.Property<string>("RuntimeSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("runtime_snapshot_json");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("ThresholdsSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("thresholds_snapshot_json");

                    b.Property<int>("TotalCases")
                        .HasColumnType("integer")
                        .HasColumnName("total_cases");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_rag_evaluation_runs");

                    b.HasIndex("DatasetId")
                        .HasDatabaseName("ix_rag_evaluation_runs_dataset_id");

                    b.HasIndex("RequestedById")
                        .HasDatabaseName("ix_rag_evaluation_runs_requested_by_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_rag_evaluation_runs_status_created_at");

                    b.ToTable("rag_evaluation_runs", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.SearchQuery", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ClickedArticleId")
                        .HasColumnType("text")
                        .HasColumnName("clicked_article_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query");

                    b.Property<string>("RagAnswerHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rag_answer_hash");

                    b.Property<string>("RagFeedback")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rag_feedback");

                    b.Property<DateTime?>("RagFeedbackAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("rag_feedback_at");

                    b.Property<string>("RagFeedbackReason")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("rag_feedback_reason");

                    b.Property<string>("RagGroundingStatus")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("rag_grounding_status");

                    b.Property<string>("RagIndexProfile")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rag_index_profile");

                    b.Property<string>("RagPromptVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rag_prompt_version");

                    b.Property<string>("RagReranker")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rag_reranker");

                    b.Property<string>("RagRetrievalVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rag_retrieval_version");

                    b.Property<string>("RagTraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rag_trace_id");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("response_time_ms");

                    b.Property<int>("ResultsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("results_count");

                    b.Property<string>("SearchType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("fulltext")
                        .HasColumnName("search_type");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_search_queries");

                    b.HasIndex("ClickedArticleId")
                        .HasDatabaseName("ix_search_queries_clicked_article_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_search_queries_user_id");

                    b.ToTable("search_queries", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_slug");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.UsageEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ApiKeyId")
                        .HasColumnType("text")
                        .HasColumnName("api_key_id");

                    b.Property<string>("AuthSource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("auth_source");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("http_method");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("operation");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_usage_events");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_usage_events_occurred_at");

                    b.HasIndex("ApiKeyId", "OccurredAt")
                        .HasDatabaseName("ix_usage_events_api_key_id_occurred_at");

                    b.HasIndex("Operation", "OccurredAt")
                        .HasDatabaseName("ix_usage_events_operation_occurred_at");

                    b.HasIndex("UserId", "OccurredAt")
                        .HasDatabaseName("ix_usage_events_user_id_occurred_at");

                    b.ToTable("usage_events", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AzureObjectId")
                        .HasColumnType("text")
                        .HasColumnName("azure_object_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("viewer")
                        .HasColumnName("role");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_users_slug");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ApiKey", b =>
                {
                    b.HasOne("KnowledgePortal.Api.Models.Entities.User", "User")
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_keys_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.Article", b =>
                {
                    b.HasOne("KnowledgePortal.Api.Models.Entities.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_articles_users_approved_by_id");

                    b.HasOne("KnowledgePortal.Api.Models.Entities.ApiKey", "CreatedViaApiKey")
                        .WithMany()
                        .HasForeignKey("CreatedViaApiKeyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_articles_api_keys_created_via_api_key_id");

                    b.HasOne("KnowledgePortal.Api.Models.Entities.User", "Owner")
                        .WithMany("Articles")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_articles_users_owner_id");

                    b.Navigation("ApprovedBy");

                    b.Navigation("CreatedViaApiKey");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleAttachment", b =>
                {
                    b.HasOne("KnowledgePortal.Api.Models.Entities.Article", "Article")
                        .WithMany("Attachments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_attachments_articles_article_id");

                    b.HasOne("KnowledgePortal.Api.Models.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_attachments_users_uploaded_by_id");

                    b.Navigation("Article");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleChunkParent", b =>
                {
                    b.HasOne("KnowledgePortal.Api.Models.Entities.Article", "Article")
                        .WithMany("ArticleChunkParents")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_chunk_parents_articles_article_id");

                    b.HasOne("KnowledgePortal.Api.Models.Entities.ArticleAttachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_article_chunk_parents_article_attachments_attachment_id");

                    b.Navigation("Article");

                    b.Navigation("Attachment");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleComment", b =>
                {
                    b.HasOne("KnowledgePortal.Api.Models.Entities.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_comments_articles_article_id");

                    b.HasOne("KnowledgePortal.Api.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_comments_users_user_id");

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleEmbedding", b =>
                {
                    b.HasOne("KnowledgePortal.Api.Models.Entities.Article", "Article")
                        .WithMany("ArticleEmbeddings")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_embeddings_articles_article_id");

                    b.HasOne("KnowledgePortal.Api.Models.Entities.ArticleAttachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_article_embeddings_article_attachments_attachment_id");

                    b.HasOne("KnowledgePortal.Api.Models.Entities.ArticleChunkParent", "ParentChunk")
                        .WithMany("Children")
                        .HasForeignKey("ParentChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_article_embeddings_article_chunk_parents_parent_chunk_id");

                    b.Navigation("Article");

                    b.Navigation("Attachment");

                    b.Navigation("ParentChunk");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleTag", b =>
                {
                    b.HasOne("KnowledgePortal.Api.Models.Entities.Article", "Article")
                        .WithMany("ArticleTags")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_tags_articles_article_id");

                    b.HasOne("KnowledgePortal.Api.Models.Entities.Tag", "Tag")
                        .WithMany("ArticleTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_tags_tags_tag_id");

                    b.Navigation("Article");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleVersion", b =>
                {
                    b.HasOne("KnowledgePortal.Api.Models.Entities.Article", "Article")
                        .WithMany("Versions")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_versions_articles_article_id");

                    b.HasOne("KnowledgePortal.Api.Models.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_versions_users_changed_by");

                    b.Navigation("Article");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleView", b =>
                {
                    b.HasOne("KnowledgePortal.Api.Models.Entities.Article", "Article")
                        .WithMany("Views")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_views_articles_article_id");

                    b.HasOne("KnowledgePortal.Api.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_article_views_users_user_id");

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleVote", b =>
                {
                    b.HasOne("KnowledgePortal.Api.Models.Entities.Article", "Article")
                        .WithMany("Votes")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_votes_articles_article_id");

                    b.HasOne("KnowledgePortal.Api.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_votes_users_user_id");

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.IndexJob", b =>
                {
                    b.HasOne("KnowledgePortal.Api.Models.Entities.Article", "Article")
                        .WithOne()
                        .HasForeignKey("KnowledgePortal.Api.Models.Entities.IndexJob", "ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_index_jobs_articles_article_id");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.RagEvaluationRun", b =>
                {
                    b.HasOne("KnowledgePortal.Api.Models.Entities.RagEvaluationDataset", "Dataset")
                        .WithMany("Runs")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rag_evaluation_runs_rag_evaluation_datasets_dataset_id");

                    b.HasOne("KnowledgePortal.Api.Models.Entities.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rag_evaluation_runs_users_requested_by_id");

                    b.Navigation("Dataset");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.SearchQuery", b =>
                {
                    b.HasOne("KnowledgePortal.Api.Models.Entities.Article", "ClickedArticle")
                        .WithMany()
                        .HasForeignKey("ClickedArticleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_search_queries_articles_clicked_article_id");

                    b.HasOne("KnowledgePortal.Api.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_search_queries_users_user_id");

                    b.Navigation("ClickedArticle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.UsageEvent", b =>
                {
                    b.HasOne("KnowledgePortal.Api.Models.Entities.ApiKey", "ApiKey")
                        .WithMany()
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_usage_events_api_keys_api_key_id");

                    b.HasOne("KnowledgePortal.Api.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_usage_events_users_user_id");

                    b.Navigation("ApiKey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.Article", b =>
                {
                    b.Navigation("ArticleChunkParents");

                    b.Navigation("ArticleEmbeddings");

                    b.Navigation("ArticleTags");

                    b.Navigation("Attachments");

                    b.Navigation("Comments");

                    b.Navigation("Versions");

                    b.Navigation("Views");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleChunkParent", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.RagEvaluationDataset", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.Tag", b =>
                {
                    b.Navigation("ArticleTags");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.User", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
