// <auto-generated />
using System;
using KnowledgePortal.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KnowledgePortal.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601175929_RemoveDeadColumns")]
    partial class RemoveDeadColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ApiKey", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("key_prefix");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("KeyPrefix");

                    b.HasIndex("UserId");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.Article", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Audience")
                        .HasColumnType("TEXT")
                        .HasColumnName("audience");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("reference")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedViaApiKeyId")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_via_api_key_id");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("beginner")
                        .HasColumnName("difficulty");

                    b.Property<string>("Excerpt")
                        .HasColumnType("TEXT")
                        .HasColumnName("excerpt");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("indexed_at");

                    b.Property<DateTime?>("LastReviewedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_reviewed_at");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_id");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("published_at");

                    b.Property<int?>("ReadTimeMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("read_time_minutes");

                    b.Property<int>("ReviewIntervalDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(90)
                        .HasColumnName("review_interval_days");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedViaApiKeyId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleFeedback", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ArticleId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("article_id");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("Helpful")
                        .HasColumnType("INTEGER")
                        .HasColumnName("helpful");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("article_feedback", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleTag", b =>
                {
                    b.Property<string>("ArticleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("article_id");

                    b.Property<string>("TagId")
                        .HasColumnType("TEXT")
                        .HasColumnName("tag_id");

                    b.HasKey("ArticleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("article_tags", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleVersion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ArticleId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("article_id");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("TEXT")
                        .HasColumnName("change_summary");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("changed_by");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ChangedBy");

                    b.ToTable("article_versions", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleView", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ArticleId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("article_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("article_views", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.SearchQuery", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ClickedArticleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("clicked_article_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("query");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("response_time_ms");

                    b.Property<int>("ResultsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("results_count");

                    b.Property<string>("SearchType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("fulltext")
                        .HasColumnName("search_type");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ClickedArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("search_queries", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Avatar")
                        .HasColumnType("TEXT")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("viewer")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ApiKey", b =>
                {
                    b.HasOne("KnowledgePortal.Api.Models.Entities.User", "User")
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.Article", b =>
                {
                    b.HasOne("KnowledgePortal.Api.Models.Entities.ApiKey", "CreatedViaApiKey")
                        .WithMany()
                        .HasForeignKey("CreatedViaApiKeyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KnowledgePortal.Api.Models.Entities.User", "Owner")
                        .WithMany("Articles")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedViaApiKey");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleFeedback", b =>
                {
                    b.HasOne("KnowledgePortal.Api.Models.Entities.Article", "Article")
                        .WithMany("Feedback")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgePortal.Api.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleTag", b =>
                {
                    b.HasOne("KnowledgePortal.Api.Models.Entities.Article", "Article")
                        .WithMany("ArticleTags")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgePortal.Api.Models.Entities.Tag", "Tag")
                        .WithMany("ArticleTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleVersion", b =>
                {
                    b.HasOne("KnowledgePortal.Api.Models.Entities.Article", "Article")
                        .WithMany("Versions")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgePortal.Api.Models.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.ArticleView", b =>
                {
                    b.HasOne("KnowledgePortal.Api.Models.Entities.Article", "Article")
                        .WithMany("Views")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgePortal.Api.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.SearchQuery", b =>
                {
                    b.HasOne("KnowledgePortal.Api.Models.Entities.Article", "ClickedArticle")
                        .WithMany()
                        .HasForeignKey("ClickedArticleId");

                    b.HasOne("KnowledgePortal.Api.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("ClickedArticle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.Article", b =>
                {
                    b.Navigation("ArticleTags");

                    b.Navigation("Feedback");

                    b.Navigation("Versions");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.Tag", b =>
                {
                    b.Navigation("ArticleTags");
                });

            modelBuilder.Entity("KnowledgePortal.Api.Models.Entities.User", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
